spring.application.name=ya-factura-back

# ===============================
# = DATA SOURCE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/db_pantalla_llamadora
spring.datasource.username=postgres
spring.datasource.password=je20142021.
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
spring.devtools.add-properties=false

# mostrar sentencias SQL en la consola
spring.jpa.show-sql = true


# security
application.security.jwt.secret-key=YWRqc2FrZGprYXNkYWprc2RhamsyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MA==
application.security.jwt.secret-key-company=ZmxqYXNkbGZqc2RsamZsc2pkbGZqc2RsZmpzbGRqZjEyMzQ1Njc4OTAxMjM0NTY3ODkw
application.security.jwt.secret-key-rider=bGthamZrc2Fka2pkZmFsa2RzamZsYWtqZHNmamsxMjM0NTY3ODkwMTIzNDU2Nzg5MA==
application.security.jwt.expiration=7200000
application.security.jwt.expiration-rider=7200000
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.security.web.DefaultSecurityFilterChain=TRACE
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=TRACE


# mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
server.port=8084
#server.addres-=127.0.0.1
server.address=0.0.0.0

app.swagger.server-url=http://localhost:8084

mail.urlFront=http://localhost:4200/change-password/

spring.mvc.contentnegotiation.favor-parameter=true
spring.mvc.contentnegotiation.media-types.pdf=application/pdf
spring.mvc.contentnegotiation.media-types.xlsx=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
spring.mvc.contentnegotiation.media-types.csv=text/csv
spring.mvc.contentnegotiation.media-types.xml=application/xml
spring.mvc.contentnegotiation.media-types.json=application/json

# HikariCP settings
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.maximum-pool-size=10


springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

gcp.project-id=tu-project-id
gcp.bucket-name=teloreparto-uploads
gcp.credentials.path=/keys/mi-servicio-gcp.json



# ===============================
# = BANCARD CONFIG
# ===============================

# Ambiente produccion
#bancard.url=https://vpos.bancard.com.py
# Ambiente TEST / SANDBOX
bancard.url=https://vpos.infonet.com.py:8888

# Claves entregadas por Bancard
bancard.public-key=I5khJFOMBfb0ZpvbKLgWe0IUbSXNgEM5
#bancard.private-key=tlT$PQbIP(NXfDo3xLqAEbRKUXPGzfRHeREF.lzb
bancard.private-key=tlT\$PQbIP(NXfDo3xLqAEbRKUXPGzfRHeREF.lzb

# Habilitar recursos estáticos desde el filesystem
spring.web.resources.static-locations=file:/opt/imagenes/
spring.mvc.static-path-pattern=/**